import {memo,useState} from 'react';
import * as Dialog from '@radix-ui/react-dialog';
import {X} from 'lucide-react';
import {useShallow} from 'zustand/react/shallow';
import {useEditorStore} from '../../store/editorStore';
import {useDocumentStore} from '../../store/documentStore';
import {useUIStore} from '../../store/uiStore';
import {documentSections} from '../../domain/manualSections';
const AdditionRow=memo(function AdditionRow({id}:{id:string}){
 const addition=useEditorStore(s=>s.config.manualSections?.find(a=>a.id===id));if(!addition)return null;
 const update=(patch:Partial<Pick<typeof addition,'text'|'title'>>)=>{const state=useEditorStore.getState();state.setManualSections((state.config.manualSections??[]).map(a=>a.id===id?{...a,...patch}:a));};
 return <div className="manual-addition"><small>{addition.documentId} · {addition.sectionKey}</small><label className="field"><span>Título de la aportación</span><input aria-label={`Título de ${id}`} value={addition.title} maxLength={100} onChange={e=>update({title:e.target.value})}/></label><label className="field"><span>Texto propio</span><textarea aria-label={`Texto de ${id}`} value={addition.text} maxLength={10000} onChange={e=>update({text:e.target.value})}/></label><button onClick={()=>{if(window.confirm('¿Eliminar esta aportación manual?')){const state=useEditorStore.getState();state.setManualSections((state.config.manualSections??[]).filter(a=>a.id!==id));}}}>Eliminar aportación</button></div>;
});
function AdditionControls(){
 const active=useUIStore(s=>s.activeDocument),raw=useDocumentStore(s=>s.pendingCompilation??s.generatedCompilation),revision=useEditorStore(s=>s.config.revision);
 const ids=useEditorStore(useShallow(s=>(s.config.manualSections??[]).map(a=>a.id)));
 const [sectionKey,setSectionKey]=useState('documento');const doc=raw?.documents.find(d=>d.id===active),sections=doc?documentSections(doc.content):[];const tooLarge=(sections.find(s=>s.key===sectionKey)?.content.length??0)>40000;
 return <><p>Documento actual: {doc?.path??'Esperando generación'}. El texto generado se conserva. Las aportaciones se añaden como bloques separados.</p><label className="field"><span>Sección de destino</span><select aria-label="Sección de destino" value={sections.some(s=>s.key===sectionKey)?sectionKey:'documento'} onChange={e=>setSectionKey(e.target.value)}>{sections.map(s=><option key={s.key} value={s.key}>{s.title}</option>)}</select></label><button disabled={!doc||raw?.revision!==revision||ids.length>=50||tooLarge} onClick={()=>{const section=sections.find(s=>s.key===sectionKey)??sections[0];if(!section||section.content.length>40000)return;const state=useEditorStore.getState();state.setManualSections([...(state.config.manualSections??[]),{id:`MAN-${crypto.randomUUID()}`,documentId:doc!.id,sectionKey:section.key,title:'Nota para revisión',text:'',baseContent:section.content}]);}}>Añadir aportación manual</button>{tooLarge&&<p>La sección supera 40000 caracteres. Elige «Final del documento» para conservar tu aportación.</p>}{ids.map(id=><AdditionRow key={id} id={id}/>)}{useEditorStore(s=>s.projectError)&&<p role="alert">{useEditorStore.getState().projectError}</p>}</>;
}
function ConflictReview(){
 const conflicts=useDocumentStore(s=>s.manualConflicts),[open,setOpen]=useState(false),[choices,setChoices]=useState<Record<string,'keep'|'detach'>>({});
 if(!conflicts.length)return null;
 return <><div role="alert" className="diagnostic"><p>Hay {conflicts.length} aportación(es) cuya sección cambió. Se conserva el texto; la nueva revisión requiere resolver sus diferencias.</p><button onClick={()=>{setChoices({});setOpen(true);}}>Revisar cambios de secciones</button></div><Dialog.Root open={open} onOpenChange={setOpen}><Dialog.Portal><Dialog.Overlay className="overlay"/><Dialog.Content className="dialog library-dialog" onCloseAutoFocus={e=>{e.preventDefault();document.querySelector<HTMLElement>('.manual-sections summary')?.focus();}}><Dialog.Title>Resolver aportaciones manuales</Dialog.Title><Dialog.Description>Compara la sección anterior y la nueva. Ninguna opción elimina tu texto. Cancelar mantiene la revisión pendiente.</Dialog.Description>{conflicts.map(c=><section key={c.additionId}><h3>{c.title} · {c.documentId}</h3><div className="section-comparison"><label>Sección anterior<pre>{c.previous||'Sin sección anterior'}</pre></label><label>Sección nueva<pre>{c.missing?'La sección ya no existe':c.next}</pre></label></div><label className="field"><span>Decisión para {c.title}</span><select aria-label={`Resolución de ${c.additionId}`} value={choices[c.additionId]??''} onChange={e=>setChoices({...choices,[c.additionId]:e.target.value as 'keep'|'detach'})}><option value="">Elige una resolución</option><option value="keep" disabled={c.missing}>Conservar aportación con la sección nueva</option><option value="detach">Mover aportación al final del documento</option></select></label></section>)}<div className="library-actions"><button className="primary" disabled={conflicts.some(c=>!choices[c.additionId])} onClick={()=>{if(useDocumentStore.getState().resolveManualConflicts(choices))setOpen(false);}}>Confirmar resolución</button><button onClick={()=>setOpen(false)}>Cancelar revisión</button></div><Dialog.Close className="close-icon" aria-label="Cerrar resolución"><X size={18}/></Dialog.Close></Dialog.Content></Dialog.Portal></Dialog.Root></>;
}
export function ManualSections(){const [open,setOpen]=useState(false);return <section className="manual-sections"><ConflictReview/><details open={open} onToggle={e=>setOpen(e.currentTarget.open)}><summary>Aportaciones manuales por sección</summary>{open&&<AdditionControls/>}</details></section>;}
