import {useRef,useState} from 'react';
import * as Dialog from '@radix-ui/react-dialog';
import {FolderOpen,X,Download,Plus,Copy} from 'lucide-react';
import {useShallow} from 'zustand/react/shallow';
import {useLibraryStore} from '../../store/projectLibraryStore';
async function download(raw:string|null,name:string){if(!raw)return;const url=URL.createObjectURL(new Blob([raw],{type:'application/json;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export function ProjectLibrary(){
 const [open,setOpen]=useState(false),[label,setLabel]=useState('');const invoker=useRef<HTMLElement|null>(null);
 const {library,initialized,busy,error,pendingComparison,replaceImports}=useLibraryStore(useShallow(s=>({library:s.library,initialized:s.initialized,busy:s.busy,error:s.error,pendingComparison:s.pendingComparison,replaceImports:s.replaceImports})));
 const actions=useLibraryStore.getState();const disabled=busy||!initialized;
 const prepare=(action:()=>void)=>{invoker.current=document.activeElement as HTMLElement;action();};
 return <><Dialog.Root open={open} onOpenChange={setOpen}><Dialog.Trigger className="library-trigger"><FolderOpen size={16}/><span>Proyectos</span></Dialog.Trigger><Dialog.Portal><Dialog.Overlay className="overlay"/><Dialog.Content className="dialog library-dialog"><Dialog.Title>Biblioteca de proyectos locales</Dialog.Title><Dialog.Description>Datos en este navegador. Hasta veinte proyectos, cinco versiones por proyecto y 2 MiB. Respalda antes de borrar datos del navegador.</Dialog.Description>
 {error&&<p role="alert" className="diagnostic">{error}</p>}<div className="library-actions"><button disabled={disabled} onClick={()=>void actions.createProject(false)}><Plus size={16}/>Nuevo proyecto</button><button disabled={disabled} onClick={()=>void actions.createProject(true)}><Copy size={16}/>Duplicar proyecto actual</button><button disabled={disabled} onClick={()=>void actions.exportProjects().then(raw=>download(raw,'biblioteca-sdd.json'))}><Download size={16}/>Respaldar biblioteca</button><button disabled={busy} onClick={()=>void actions.exportCurrent().then(raw=>download(raw,'borrador-sdd.json'))}>Respaldar borrador actual</button></div>
 <label className="field"><span>Importar respaldo JSON</span><input type="file" accept=".json,application/json" disabled={disabled} onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;if(file.size>2*1024*1024){useLibraryStore.setState({error:'El respaldo supera el límite de 2 MiB.'});return;}invoker.current=e.target;void file.text().then(raw=>actions.prepareImport(raw)).catch(()=>useLibraryStore.setState({error:'No se pudo leer el archivo. Los proyectos se conservan.'}));}}/></label>
 <div className="library-actions"><label className="field"><span>Nombre de la versión</span><input maxLength={80} value={label} onChange={e=>setLabel(e.target.value)}/></label><button disabled={disabled} onClick={()=>void actions.saveVersion(label)}>Guardar versión actual</button></div>
 <p role="status">{busy?'Procesando localmente…':`${library.projects.length} / 20 proyectos`}</p>
 <div className="project-list">{library.projects.map(p=><section className="local-project" key={p.id} aria-label={`Proyecto ${p.draft.name}`}><h3>{p.draft.name}{p.id===library.activeId?' · Activo':''}</h3><small>{p.id} · {new Date(p.updatedAt).toLocaleString('es')}</small><div className="library-actions"><button disabled={disabled||p.id===library.activeId} onClick={()=>prepare(()=>actions.prepareOpen(p.id))}>Comparar y abrir</button><button disabled={disabled} onClick={()=>void actions.exportProjects(p.id).then(raw=>download(raw,`${p.draft.slug}-respaldo.json`))}>Respaldar proyecto</button><button disabled={disabled} onClick={()=>{if(window.confirm(`¿Eliminar el proyecto «${p.draft.name}» y todas sus versiones? Conserva un respaldo antes de continuar.`))void actions.deleteProject(p.id);}}>Eliminar proyecto</button></div>
 <ul className="version-list">{p.versions.map(v=><li key={v.id}><span>{v.label} · {new Date(v.createdAt).toLocaleString('es')}</span><div className="library-actions"><button disabled={disabled} onClick={()=>prepare(()=>actions.prepareRestore(p.id,v.id))}>Comparar y recuperar</button><button disabled={disabled} onClick={()=>{if(window.confirm(`¿Eliminar la versión «${v.label}»?`))void actions.deleteVersion(p.id,v.id);}}>Eliminar versión</button></div></li>)}</ul></section>)}</div><Dialog.Close className="close-icon" aria-label="Cerrar biblioteca"><X size={18}/></Dialog.Close></Dialog.Content></Dialog.Portal></Dialog.Root>
 <Dialog.Root open={!!pendingComparison} onOpenChange={value=>{if(!value)actions.cancelComparison();}}><Dialog.Portal><Dialog.Overlay className="overlay"/><Dialog.Content className="dialog library-dialog" onCloseAutoFocus={e=>{e.preventDefault();invoker.current?.focus();}}><Dialog.Title>Comparar cambios</Dialog.Title><Dialog.Description>{pendingComparison?.source}. Revisa antes de confirmar; cancelar conserva la edición y el almacenamiento.</Dialog.Description>
 {pendingComparison?.kind==='import'&&<><p>Se importarán todos los proyectos del respaldo como copias nuevas. No se abre ni sustituye tu proyecto activo.</p><label className="context-reference"><input type="checkbox" checked={replaceImports} onChange={e=>actions.setImportReplacement(e.target.checked)}/><span>Sustituir proyectos con IDs coincidentes y conservar copia previa</span></label>{replaceImports&&<p>Los estados anteriores se conservan como proyectos separados. Si falta cuota, la operación completa se rechaza.</p>}</>}
 <p>{pendingComparison?.differences.total??0} diferencias de contenido. Las revisiones técnicas no cuentan como cambios de contenido.</p><div className="diff-scroll" role="region" aria-label="Diferencias del proyecto" tabIndex={0}><table><thead><tr><th>Campo</th><th>Antes</th><th>Después</th></tr></thead><tbody>{pendingComparison?.differences.entries.map((d,i)=><tr key={`${d.path}-${i}`}><th>{d.path}</th><td><pre>{d.before}</pre></td><td><pre>{d.after}</pre></td></tr>)}</tbody></table></div>{(pendingComparison?.differences.total??0)>200&&<p>Se muestran las primeras 200 diferencias. El respaldo conserva todo el contenido.</p>}{error&&<p role="alert">{error}</p>}<div className="library-actions"><button className="primary" disabled={busy} onClick={()=>void actions.confirmComparison()}>Confirmar cambios</button><button disabled={busy} onClick={()=>actions.cancelComparison()}>Cancelar comparación</button></div><Dialog.Close className="close-icon" aria-label="Cerrar comparación"><X size={18}/></Dialog.Close></Dialog.Content></Dialog.Portal></Dialog.Root></>;
}
