import { memo, useRef, useState } from 'react';
import type { ChangeEvent } from 'react';
import * as Dialog from '@radix-ui/react-dialog';
import { Plus, Trash2, Download, X } from 'lucide-react';
import { useShallow } from 'zustand/react/shallow';
import { builtinProfiles } from '../../catalog/profiles';
import { componentKinds, componentLabels, emptyProfiles, isProfileConfiguration, modeLabels, profileLimits, profileWarnings, technologyRoles, workModes, type CustomTechnology, type DeclarativeProfile, type ProfileConfiguration, type ProjectComponent, type ProfileMetadata } from '../../domain/profiles';
import { useEditorStore } from '../../store/editorStore';
const newId=(prefix:string)=>`${prefix}-${crypto.randomUUID()}`;
const lines=(value:string)=>value.split('\n');
function useDraft<T>(value:T){const key=JSON.stringify(value);const [state,setState]=useState({key,draft:structuredClone(value)});if(state.key!==key)setState({key,draft:structuredClone(value)});return [state.draft,(draft:T)=>setState({key,draft})] as const;}
function revisionAge(date:string){if(!date)return 'Revisión pendiente';const days=Math.floor((Date.now()-new Date(date+'T00:00:00Z').getTime())/86400000);return days<0?'Fecha futura declarada; revisar':`Revisado el ${date}; antigüedad: ${days} días${days>365?' · revisar vigencia':''}`;}
function Metadata({value,onChange,id}:{value:ProfileMetadata;onChange:(patch:Partial<ProfileMetadata>)=>void;id:string}){
 return <div className="profile-fields"><label className="field"><span>Versión declarada de {id}</span><input maxLength={80} value={value.version} onChange={e=>onChange({version:e.target.value})}/></label><label className="field"><span>Fecha de revisión de {id}</span><input type="date" value={value.reviewedAt} onChange={e=>onChange({reviewedAt:e.target.value})}/></label><label className="field"><span>Fuentes HTTPS de {id}, una por línea</span><textarea rows={2} value={value.sources.map(s=>s.url).join('\n')} onChange={e=>onChange({sources:(e.target.value?e.target.value.split('\n'):[]).map(url=>({url,label:value.sources.find(s=>s.url===url)?.label??'Fuente aportada'}))})}/></label><p>{revisionAge(value.reviewedAt)}</p></div>;
}
function remove(label:string,action:()=>void){if(window.confirm(`¿Eliminar ${label}? Se conservará si todavía tiene referencias.`))action();}
const TechnologyRow=memo(function TechnologyRow({item,onSave,onRemove}:{item:CustomTechnology;onSave:(item:CustomTechnology)=>void;onRemove:()=>void}){
 const [draft,setDraft]=useDraft(item);const patch=(p:Partial<CustomTechnology>)=>setDraft({...draft,...p});
 return <fieldset className="profile-card"><legend>{item.name} · Declarada por el usuario</legend><p className="profile-identity">{item.id}</p><label className="field"><span>Nombre de tecnología propia</span><input maxLength={100} value={draft.name} onChange={e=>patch({name:e.target.value})}/></label><label className="field"><span>Función de tecnología propia</span><select value={draft.role} onChange={e=>patch({role:e.target.value as CustomTechnology['role']})}>{technologyRoles.map(r=><option key={r} value={r}>{r==='base-datos'?'Base de datos':r[0].toUpperCase()+r.slice(1)}</option>)}</select></label><label className="field"><span>Propósito de tecnología propia</span><textarea rows={2} maxLength={2000} value={draft.purpose} onChange={e=>patch({purpose:e.target.value})}/></label><label className="field"><span>Restricciones de tecnología propia, una por línea</span><textarea rows={2} value={draft.constraints.join('\n')} onChange={e=>patch({constraints:lines(e.target.value)})}/></label><Metadata value={draft} id={item.id} onChange={p=>patch(p as Partial<CustomTechnology>)}/><div className="profile-actions"><button onClick={()=>onSave(draft)}>Guardar tecnología propia</button><button onClick={()=>remove(item.name,onRemove)}><Trash2 size={16}/>Eliminar tecnología propia</button></div><small>Los campos se aplican al guardar. Registrar la tecnología no verifica su compatibilidad ni la incorpora al motor de inferencia.</small></fieldset>;
});
const ComponentRow=memo(function ComponentRow({item,value,onSave,onRemove}:{item:ProjectComponent;value:ProfileConfiguration;onSave:(item:ProjectComponent)=>void;onRemove:()=>void}){
 const [draft,setDraft]=useDraft(item);const patch=(p:Partial<ProjectComponent>)=>setDraft({...draft,...p});const toggle=(key:'dependsOn'|'technologyIds',id:string,checked:boolean)=>patch({[key]:checked?[...draft[key],id]:draft[key].filter(x=>x!==id)});
 return <fieldset className="profile-card"><legend>{item.name} · {componentLabels[item.kind]}</legend><p className="profile-identity">{item.id}</p><label className="field"><span>Nombre del componente</span><input maxLength={100} value={draft.name} onChange={e=>patch({name:e.target.value})}/></label><label className="field"><span>Tipo del componente</span><select value={draft.kind} onChange={e=>patch({kind:e.target.value as ProjectComponent['kind']})}>{componentKinds.map(k=><option key={k} value={k}>{componentLabels[k]}</option>)}</select></label><label className="field"><span>Responsabilidad del componente</span><textarea rows={2} maxLength={2000} value={draft.responsibility} onChange={e=>patch({responsibility:e.target.value})}/></label><label className="field"><span>Perfil del componente</span><select value={draft.profileId} onChange={e=>patch({profileId:e.target.value})}><option value="">Pendiente de seleccionar</option>{value.profiles.map(p=><option key={p.id} value={p.id}>{p.name} · {p.version||'Versión pendiente'}</option>)}</select></label><details><summary>Dependencias y tecnologías de {item.name}</summary>{value.components.filter(c=>c.id!==item.id).map(c=><label className="context-reference" key={c.id}><input type="checkbox" checked={draft.dependsOn.includes(c.id)} onChange={e=>toggle('dependsOn',c.id,e.target.checked)}/><span>Depende de {c.name}</span></label>)}{value.technologies.map(t=><label className="context-reference" key={t.id}><input type="checkbox" checked={draft.technologyIds.includes(t.id)} onChange={e=>toggle('technologyIds',t.id,e.target.checked)}/><span>Usa {t.name}</span></label>)}</details><div className="profile-actions"><button onClick={()=>onSave(draft)}>Guardar componente</button><button onClick={()=>remove(item.name,onRemove)}><Trash2 size={16}/>Eliminar componente</button></div><small>Los campos se aplican al guardar. El ID enlaza este componente con los requisitos del editor estructurado.</small></fieldset>;
});
const ProfileRow=memo(function ProfileRow({item,onSave,onRemove}:{item:DeclarativeProfile;onSave:(p:DeclarativeProfile)=>void;onRemove:()=>void}){
 const [draft,setDraft]=useDraft(item);const patch=(p:Partial<DeclarativeProfile>)=>setDraft({...draft,...p});
 return <fieldset className="profile-card"><legend>{item.name} · {item.support==='verificada'?'Verificada':'Declarada por el usuario'}</legend><p className="profile-identity">{item.id} · {item.version||'Versión pendiente'} · {revisionAge(item.reviewedAt)}</p>{item.support==='declarada'&&<><label className="field"><span>Nombre del perfil propio</span><input maxLength={100} value={draft.name} onChange={e=>patch({name:e.target.value})}/></label><label className="field"><span>Descripción del perfil propio</span><textarea rows={2} maxLength={2000} value={draft.description} onChange={e=>patch({description:e.target.value})}/></label><fieldset><legend>Modos aplicables</legend>{workModes.map(mode=><label className="context-reference" key={mode}><input type="checkbox" checked={draft.appliesTo.includes(mode)} onChange={e=>patch({appliesTo:e.target.checked?[...draft.appliesTo,mode]:draft.appliesTo.filter(m=>m!==mode)})}/><span>{modeLabels[mode]}</span></label>)}</fieldset><fieldset><legend>Tipos de componente aplicables</legend>{componentKinds.map(kind=><label className="context-reference" key={kind}><input type="checkbox" checked={draft.componentKinds.includes(kind)} onChange={e=>patch({componentKinds:e.target.checked?[...draft.componentKinds,kind]:draft.componentKinds.filter(k=>k!==kind)})}/><span>{componentLabels[kind]}</span></label>)}</fieldset>{(['capabilities','questions','constraints','sections'] as const).map(key=><label className="field" key={key}><span>{{capabilities:'Capacidades',questions:'Preguntas',constraints:'Restricciones',sections:'Secciones'}[key]} del perfil propio, una por línea</span><textarea rows={2} value={draft[key].join('\n')} onChange={e=>patch({[key]:lines(e.target.value)})}/></label>)}<Metadata value={draft} id={item.id} onChange={p=>patch(p)}/><button onClick={()=>onSave(draft)}>Guardar perfil propio</button></>}<ul>{item.questions.map(q=><li key={q}>{q}</li>)}</ul><button onClick={()=>remove(item.name,onRemove)}><Trash2 size={16}/>Retirar perfil</button></fieldset>;
});
function ProfilesPanel(){
 const {profile,mode,implementationRequired,error,save,setMode}=useEditorStore(useShallow(s=>({profile:s.config.profile,mode:s.config.project?.mode??'nuevo',implementationRequired:s.config.project?.implementationRequired??true,error:s.projectError,save:s.setProfileConfiguration,setMode:s.setWorkMode})));
 const project={mode,implementationRequired};
 const value=profile??emptyProfiles();const [localError,setLocalError]=useState(''),[pending,setPending]=useState<{value:ProfileConfiguration;revision:number}|null>(null);const invoker=useRef<HTMLInputElement|null>(null);
 const commit=(next:ProfileConfiguration)=>{setLocalError('');const clean=(metadata:ProfileMetadata)=>({...metadata,sources:metadata.sources.filter(s=>s.url.trim()).map(s=>({...s,url:s.url.trim()}))});return save({...next,profiles:next.profiles.map(p=>({...p,...clean(p)})),technologies:next.technologies.map(t=>({...t,...clean(t),support:'declarada' as const}))});};
 const importFile=async(e:ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];invoker.current=e.target;e.target.value='';if(!file)return;if(file.size>profileLimits.bytes){setLocalError('El archivo de perfiles supera 128 KiB.');return;}const revision=useEditorStore.getState().config.revision;try{const parsed:unknown=JSON.parse(await file.text());if(!isProfileConfiguration(parsed)){setLocalError('El JSON contiene perfiles inválidos, código, referencias o campos no permitidos.');return;}setLocalError('');setPending({value:parsed,revision});}catch{setLocalError('No se pudo leer un JSON de perfiles válido. Los datos se conservan.');}};
 const exportFile=()=>{const blob=new Blob([JSON.stringify(value,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='perfiles-sdd.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 const warnings=profileWarnings(profile,project);
 return <div className="profiles-body" role="region" aria-label="Perfiles y componentes del proyecto"><p>Perfiles declarativos, sin código ni consultas externas. Los campos de las fichas se aplican al guardar; los cambios pendientes no forman parte del respaldo. Verificada acredita estructura/proyección del generador, no la implementación ni compatibilidad real del destino.</p><label className="field"><span>Modo del proyecto</span><select value={project?.mode??'nuevo'} onChange={e=>setMode(e.target.value as typeof workModes[number])}>{workModes.map(m=><option key={m} value={m}>{modeLabels[m]}</option>)}</select></label>{project?.mode!=='nuevo'&&<p>{project?.mode==='documentacion'?'Documentación sin tareas de software; las selecciones anteriores se conservan.':'Preservar interfaces existentes y concretar compatibilidad, respaldo y alcance del cambio.'}</p>}
 {(localError||error)&&<p role="alert">{localError||error}</p>}
 <h3>Perfiles integrados</h3><div className="profile-actions">{builtinProfiles.map(p=><button key={p.id} aria-pressed={value.profiles.some(x=>x.id===p.id)} disabled={value.profiles.some(x=>x.id===p.id)||value.profiles.length>=10} onClick={()=>commit({...value,profiles:[...value.profiles,structuredClone(p)]})}>Añadir {p.name}</button>)}</div>
 <button disabled={value.profiles.length>=10} onClick={()=>commit({...value,profiles:[...value.profiles,{id:newId('PER'),name:'Perfil propio',description:'',version:'',sources:[],reviewedAt:'',support:'declarada',appliesTo:[project?.mode??'nuevo'],componentKinds:['otro'],capabilities:[],questions:[],constraints:[],sections:[]}]})}><Plus size={16}/>Añadir perfil propio</button>
 {value.profiles.map(item=><ProfileRow key={item.id} item={item} onSave={p=>commit({...value,profiles:value.profiles.map(x=>x.id===p.id?p:x)})} onRemove={()=>commit({...value,profiles:value.profiles.filter(x=>x.id!==item.id)})}/>)}
 <h3>Componentes del proyecto</h3><p>Declara web, móvil y API como componentes independientes. Sus dependencias y tecnologías propias se conservan por ID; los ciclos se rechazan.</p><button disabled={value.components.length>=20} onClick={()=>commit({...value,components:[...value.components,{id:newId('CMP'),name:'Nuevo componente',kind:'otro',responsibility:'',profileId:'',dependsOn:[],technologyIds:[]}]})}><Plus size={16}/>Añadir componente</button>
 {value.components.map(item=><ComponentRow key={item.id} item={item} value={value} onSave={c=>commit({...value,components:value.components.map(x=>x.id===c.id?c:x)})} onRemove={()=>commit({...value,components:value.components.filter(x=>x.id!==item.id)})}/>)}
 <h3>Tecnologías y protocolos propios</h3><button disabled={value.technologies.length>=50} onClick={()=>commit({...value,technologies:[...value.technologies,{id:newId('TEC'),name:'Tecnología propia',role:'otro',purpose:'',constraints:[],version:'',sources:[],reviewedAt:'',support:'declarada'}]})}><Plus size={16}/>Añadir tecnología propia</button>
 {value.technologies.map(item=><TechnologyRow key={item.id} item={item} onSave={t=>commit({...value,technologies:value.technologies.map(x=>x.id===t.id?t:x)})} onRemove={()=>commit({...value,technologies:value.technologies.filter(x=>x.id!==item.id)})}/>)}
 {warnings.length>0&&<details className="profile-warnings"><summary>Incertidumbres y aplicabilidad ({warnings.length})</summary><ul>{warnings.map((w,i)=><li key={i}>{w}</li>)}</ul></details>}
 <p>{value.profiles.length}/10 perfiles; {value.components.length}/20 componentes; {value.technologies.length}/50 tecnologías. Máximo 128 KiB.</p><div className="profile-actions"><button onClick={exportFile}><Download size={16}/>Exportar perfiles JSON</button><label className="field"><span>Importar perfiles JSON</span><input type="file" accept=".json,application/json" onChange={e=>void importFile(e)}/></label></div>
 <Dialog.Root open={!!pending} onOpenChange={open=>{if(!open)setPending(null);}}><Dialog.Portal><Dialog.Overlay className="overlay"/><Dialog.Content className="dialog" onCloseAutoFocus={e=>{e.preventDefault();invoker.current?.focus();}}><Dialog.Title>Revisar importación de perfiles</Dialog.Title><Dialog.Description>Se sustituirán solo perfiles, componentes y tecnologías propias tras confirmar. Los requisitos, textos, diseño y aportaciones se conservan. La biblioteca permite guardar una versión previa.</Dialog.Description><p>Actual: {value.profiles.length} perfiles, {value.components.length} componentes, {value.technologies.length} tecnologías. Importación: {pending?.value.profiles.length} perfiles, {pending?.value.components.length} componentes, {pending?.value.technologies.length} tecnologías.</p><ul>{pending?.value.profiles.map(p=><li key={p.id}>{p.name} · {p.version||'Versión pendiente'} · {p.support==='verificada'?'Verificada':'Declarada por el usuario'}</li>)}</ul>{(localError||error)&&<p role="alert">{localError||error}</p>}<div className="dialog-actions"><button onClick={()=>{if(!pending)return;if(useEditorStore.getState().config.revision!==pending.revision){setLocalError('La edición cambió durante la comparación. Cancela e importa de nuevo.');setPending(null);return;}if(commit(pending.value))setPending(null);}}>Confirmar importación de perfiles</button><Dialog.Close>Cancelar importación</Dialog.Close></div><Dialog.Close className="close-icon" aria-label="Cerrar importación"><X size={18}/></Dialog.Close></Dialog.Content></Dialog.Portal></Dialog.Root></div>;
}
export function ProfileStudio(){const [open,setOpen]=useState(false);const projectId=useEditorStore(s=>s.config.project?.projectId??s.config.slug);return <details className="profile-studio" onToggle={e=>setOpen(e.currentTarget.open)}><summary>Perfiles y componentes</summary>{open&&<ProfilesPanel key={projectId}/>}</details>;}
