export interface Archetype { id: string; name: string; background: string; surface: string; accent: string; secondaryAccent: string; foreground: string; muted: string; border: string; heading: string; body: string; radius: number; texture: string }
export const archetypes: Archetype[] = [
  {
    "id": "a01",
    "name": "Prensa editorial independiente",
    "background": "#FBFBF9",
    "surface": "#F2EFE9",
    "accent": "#C2593F",
    "secondaryAccent": "",
    "foreground": "#141413",
    "muted": "#75736C",
    "border": "#E5E1D8",
    "heading": "Cormorant Garamond",
    "body": "Space Grotesk",
    "radius": 4,
    "texture": "plano, grano de papel"
  },
  {
    "id": "a02",
    "name": "Terminal ciberpunk / Matrix",
    "background": "#08090A",
    "surface": "#101416",
    "accent": "#00FF88",
    "secondaryAccent": "",
    "foreground": "#E5E7EB",
    "muted": "#64748B",
    "border": "#1E293B",
    "heading": "JetBrains Mono",
    "body": "Fira Code",
    "radius": 0,
    "texture": "plano, líneas de barrido"
  },
  {
    "id": "a03",
    "name": "Pizarra minimalista nórdica",
    "background": "#F8FAFC",
    "surface": "#FFFFFF",
    "accent": "#2563EB",
    "secondaryAccent": "",
    "foreground": "#0F172A",
    "muted": "#64748B",
    "border": "#E2E8F0",
    "heading": "Plus Jakarta Sans",
    "body": "Inter",
    "radius": 8,
    "texture": "sombra suave, espacio limpio"
  },
  {
    "id": "a04",
    "name": "Precisión suiza para software",
    "background": "#111215",
    "surface": "#18191E",
    "accent": "#2D5CF6",
    "secondaryAccent": "",
    "foreground": "#FFFFFF",
    "muted": "#9CA3AF",
    "border": "#262830",
    "heading": "Geist Sans",
    "body": "Inter",
    "radius": 6,
    "texture": "microbordes de 1 px"
  },
  {
    "id": "a05",
    "name": "Pop neobrutalista",
    "background": "#FFFDF5",
    "surface": "#FFFFFF",
    "accent": "#FF5D00",
    "secondaryAccent": "#FFE600",
    "foreground": "#000000",
    "muted": "#4B5563",
    "border": "#000000",
    "heading": "Archivo Black",
    "body": "Public Sans",
    "radius": 0,
    "texture": "borde 2,5 px, sombra dura 4 px × 4 px negra"
  },
  {
    "id": "a06",
    "name": "Tierra orgánica y micelio",
    "background": "#181614",
    "surface": "#26231F",
    "accent": "#BC6C25",
    "secondaryAccent": "#52796F",
    "foreground": "#EDE0D4",
    "muted": "#A39688",
    "border": "#38332D",
    "heading": "Fraunces",
    "body": "Cabinet Grotesk",
    "radius": 12,
    "texture": "ruido terrestre sutil"
  },
  {
    "id": "a07",
    "name": "Lujo de obsidiana monocromática",
    "background": "#050505",
    "surface": "#0D0D0F",
    "accent": "#D4AF37",
    "secondaryAccent": "",
    "foreground": "#F4F4F5",
    "muted": "#A1A1AA",
    "border": "#1F1F24",
    "heading": "Playfair Display",
    "body": "Satoshi",
    "radius": 2,
    "texture": "bisel, resplandor contenido"
  },
  {
    "id": "a08",
    "name": "Onda sintética retro de Tokio",
    "background": "#120D1D",
    "surface": "#1D152E",
    "accent": "#00F0FF",
    "secondaryAccent": "#FF007F",
    "foreground": "#F5F3FF",
    "muted": "#938BA1",
    "border": "#352554",
    "heading": "Syne",
    "body": "Space Mono",
    "radius": 10,
    "texture": "sombras luminosas de neón"
  },
  {
    "id": "a09",
    "name": "Horizonte técnico solarizado",
    "background": "#002B36",
    "surface": "#073642",
    "accent": "#B58900",
    "secondaryAccent": "#2AA198",
    "foreground": "#93A1A1",
    "muted": "#657B83",
    "border": "#0D4958",
    "heading": "Inconsolata",
    "body": "Source Sans 3",
    "radius": 4,
    "texture": "acabado mate"
  },
  {
    "id": "a10",
    "name": "Aura de cristal esmerilado",
    "background": "#0A0B12",
    "surface": "rgba(255,255,255,0.04)",
    "accent": "#8B5CF6",
    "secondaryAccent": "",
    "foreground": "#F8FAFC",
    "muted": "#94A3B8",
    "border": "rgba(255,255,255,0.12)",
    "heading": "Outfit",
    "body": "Inter",
    "radius": 16,
    "texture": "desenfoque 24 px y luz flotante"
  },
  {
    "id": "a11",
    "name": "Carbón wabi-sabi japonés",
    "background": "#1E1E20",
    "surface": "#28282B",
    "accent": "#C84B31",
    "secondaryAccent": "",
    "foreground": "#DCD6CD",
    "muted": "#8A857D",
    "border": "#38383C",
    "heading": "Shippori Mincho",
    "body": "Zen Kaku Gothic",
    "radius": 0,
    "texture": "mate táctil"
  },
  {
    "id": "a12",
    "name": "Mar profundo bioluminiscente",
    "background": "#020B14",
    "surface": "#061A29",
    "accent": "#00E5FF",
    "secondaryAccent": "",
    "foreground": "#E0F7FA",
    "muted": "#5C8296",
    "border": "#0D344D",
    "heading": "Clash Display",
    "body": "General Sans",
    "radius": 14,
    "texture": "viñeta oceánica, bordes luminosos"
  },
  {
    "id": "a13",
    "name": "Monolito industrial",
    "background": "#191A1C",
    "surface": "#242629",
    "accent": "#F59E0B",
    "secondaryAccent": "",
    "foreground": "#E5E7EB",
    "muted": "#9CA3AF",
    "border": "#373A40",
    "heading": "Chivo",
    "body": "DM Mono",
    "radius": 2,
    "texture": "chaflán, espaciado compacto"
  },
  {
    "id": "a14",
    "name": "Calidez del desierto de Sedona",
    "background": "#FDFAF6",
    "surface": "#F5EDE4",
    "accent": "#9C4125",
    "secondaryAccent": "",
    "foreground": "#2B2623",
    "muted": "#7C7067",
    "border": "#E5D9CC",
    "heading": "Cormorant Infant",
    "body": "Switzer",
    "radius": 8,
    "texture": "superficies cálidas"
  },
  {
    "id": "a15",
    "name": "Cafetería de espresso aterciopelado",
    "background": "#141110",
    "surface": "#211C1A",
    "accent": "#D97706",
    "secondaryAccent": "",
    "foreground": "#F5EBE0",
    "muted": "#96867B",
    "border": "#3B322D",
    "heading": "Newsreader",
    "body": "Epilogue",
    "radius": 10,
    "texture": "profundidad cálida"
  },
  {
    "id": "a16",
    "name": "Titanio de sala limpia aeroespacial",
    "background": "#0E1117",
    "surface": "#161B22",
    "accent": "#FF5C00",
    "secondaryAccent": "",
    "foreground": "#E6EDF3",
    "muted": "#8B949E",
    "border": "#30363D",
    "heading": "Space Grotesk",
    "body": "Geist Mono",
    "radius": 4,
    "texture": "retícula precisa"
  },
  {
    "id": "a17",
    "name": "Musgo de bosque otoñal",
    "background": "#0D1612",
    "surface": "#16231D",
    "accent": "#22C55E",
    "secondaryAccent": "#A16207",
    "foreground": "#ECFDF5",
    "muted": "#6B8F7D",
    "border": "#22382E",
    "heading": "Instrument Serif",
    "body": "Albert Sans",
    "radius": 12,
    "texture": "sombras orgánicas suaves"
  },
  {
    "id": "a18",
    "name": "Brutalismo ácido Y2K",
    "background": "#0C0C0C",
    "surface": "#171717",
    "accent": "#CCFF00",
    "secondaryAccent": "",
    "foreground": "#FFFFFF",
    "muted": "#888888",
    "border": "#262626",
    "heading": "Syne ExtraBold",
    "body": "JetBrains Mono",
    "radius": 0,
    "texture": "insignias gruesas redondeadas"
  },
  {
    "id": "a19",
    "name": "Zafiro de medianoche art déco",
    "background": "#070E1B",
    "surface": "#0E182B",
    "accent": "#C5A059",
    "secondaryAccent": "",
    "foreground": "#F1F5F9",
    "muted": "#64748B",
    "border": "#1E304F",
    "heading": "Cinzel",
    "body": "Manrope",
    "radius": 6,
    "texture": "simetría y brillo metálico sutil"
  },
  {
    "id": "a20",
    "name": "Lujo sereno de lino y arena",
    "background": "#F7F5F0",
    "surface": "#ECE7DE",
    "accent": "#556B2F",
    "secondaryAccent": "",
    "foreground": "#202020",
    "muted": "#66635D",
    "border": "#DED7CB",
    "heading": "Bespoke Serif",
    "body": "General Sans",
    "radius": 6,
    "texture": "sin sombra, espacio amplio"
  },
  {
    "id": "a21",
    "name": "Orquídea botánica oscura",
    "background": "#0B120D",
    "surface": "#122017",
    "accent": "#E11D48",
    "secondaryAccent": "",
    "foreground": "#ECFDF5",
    "muted": "#718C7B",
    "border": "#1E3827",
    "heading": "Playfair Display",
    "body": "Urbanist",
    "radius": 16,
    "texture": "superficies aterciopeladas"
  }
];
export const archetypeById = new Map(archetypes.map(a => [a.id,a]));
