import { test,expect,type Page } from '@playwright/test';
import { readFile } from 'node:fs/promises';
import JSZip from 'jszip';
import { builtinProfiles } from '../../src/catalog/profiles';
import { emptyProfiles } from '../../src/domain/profiles';
import { emptyConfiguration } from '../../src/domain/models';
async function panel(page:Page){await page.goto('./');if((await page.viewportSize())!.width<1280)await page.getByRole('button',{name:'Configuración',exact:true}).click();await page.getByText('Perfiles y componentes',{exact:true}).click();return page.getByRole('region',{name:'Perfiles y componentes del proyecto'});}
test('tecnología propia, modo y componentes llegan al kit y sobreviven a recarga',async({page})=>{
 const region=await panel(page);await region.getByRole('button',{name:'Añadir tecnología propia',exact:true}).click();await region.getByLabel('Nombre de tecnología propia',{exact:true}).fill('Protocolo del laboratorio');await region.getByRole('combobox',{name:'Función de tecnología propia',exact:true}).selectOption('protocolo');await region.getByLabel('Propósito de tecnología propia',{exact:true}).fill('Medir sin conectividad');await region.getByRole('button',{name:'Guardar tecnología propia',exact:true}).click();
 await region.getByRole('button',{name:'Añadir Sistemas, datos y dispositivos',exact:true}).click();await region.getByRole('button',{name:'Añadir componente',exact:true}).click();await region.getByLabel('Nombre del componente',{exact:true}).fill('Instrumento científico');await region.getByLabel('Responsabilidad del componente',{exact:true}).fill('Registrar mediciones');await region.getByRole('combobox',{name:'Perfil del componente',exact:true}).selectOption('perfil-sistema');await region.getByText('Dependencias y tecnologías de Nuevo componente',{exact:true}).click();await region.getByLabel('Usa Protocolo del laboratorio',{exact:true}).check();await region.getByRole('button',{name:'Guardar componente',exact:true}).click();
 await region.getByRole('combobox',{name:'Modo del proyecto',exact:true}).selectOption('ampliacion');const button=page.getByRole('button',{name:'Descargar Kit SDD (.zip)',exact:true});await expect(button).toBeEnabled();const [download]=await Promise.all([page.waitForEvent('download'),button.click()]);const zip=await JSZip.loadAsync(await readFile((await download.path())!));expect(Object.values(zip.files).filter(f=>!f.dir)).toHaveLength(34);const spec=await zip.file('specs/001-mi-proyecto/spec.md')!.async('string');expect(spec).toContain('Protocolo del laboratorio');expect(spec).toContain('Declarada por el usuario');const tasks=await zip.file('specs/001-mi-proyecto/tasks.md')!.async('string');expect(tasks).toContain('máximo tres');expect(tasks).toContain('Puerta de aprobación');
 await page.reload();if((await page.viewportSize())!.width<1280)await page.getByRole('button',{name:'Configuración',exact:true}).click();if(await page.locator('.profile-studio').getAttribute('open')===null)await page.getByText('Perfiles y componentes',{exact:true}).click();await expect(region.getByLabel('Modo del proyecto')).toHaveValue('ampliacion');await expect(region.getByLabel('Nombre de tecnología propia')).toHaveValue('Protocolo del laboratorio');
});
test('importación de perfiles cancela sin cambios, confirma y rechaza código',async({page})=>{
 const region=await panel(page),input=region.getByLabel('Importar perfiles JSON',{exact:true});const profile={...emptyProfiles(),profiles:[structuredClone(builtinProfiles[4])]};const before=await page.evaluate(()=>localStorage.getItem('sdd-studio:biblioteca:v1'));
 await input.setInputFiles({name:'perfiles.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(profile))});await expect(page.getByRole('dialog',{name:'Revisar importación de perfiles'})).toBeVisible();await page.getByRole('button',{name:'Cancelar importación',exact:true}).click();await expect(input).toBeFocused();expect(await page.evaluate(()=>localStorage.getItem('sdd-studio:biblioteca:v1'))).toBe(before);
 await input.setInputFiles({name:'perfiles.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(profile))});await page.getByRole('button',{name:'Confirmar importación de perfiles',exact:true}).click();await expect(region.locator('legend').filter({hasText:'Proceso documental · Verificada'})).toBeVisible();await region.getByLabel('Modo del proyecto').selectOption('documentacion');await expect(region).toContainText('Documentación sin tareas de software');
 const malicious={...profile,profiles:[{...profile.profiles[0],script:'alert(1)'}]};await input.setInputFiles({name:'inseguro.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(malicious))});await expect(region.getByRole('alert')).toContainText('campos no permitidos');await expect(page.getByRole('dialog',{name:'Revisar importación de perfiles'})).toHaveCount(0);
});
for(const width of [375,768,1280])test(`perfiles permiten teclado y no desbordan a ${width}px`,async({page})=>{
 await page.setViewportSize({width,height:1000});const region=await panel(page);await region.getByRole('button',{name:'Añadir perfil propio',exact:true}).click();await region.getByRole('button',{name:'Añadir componente',exact:true}).click();await region.getByRole('button',{name:'Añadir tecnología propia',exact:true}).click();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 const mode=region.getByLabel('Modo del proyecto');await mode.focus();await page.keyboard.press('ArrowDown');await page.keyboard.press('Enter');await expect(mode).toHaveValue('ampliacion');
 const json={...emptyProfiles(),profiles:[structuredClone(builtinProfiles[0])]};const input=region.getByLabel('Importar perfiles JSON');await input.setInputFiles({name:'perfiles.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(json))});const dialog=page.getByRole('dialog',{name:'Revisar importación de perfiles'});await expect(dialog).toBeVisible();for(let i=0;i<8;i++){await page.keyboard.press('Tab');expect(await dialog.evaluate(d=>d.contains(document.activeElement))).toBe(true);}await page.keyboard.press('Escape');await expect(input).toBeFocused();
});
test('la edición de tecnologías propias mantiene p95 menor de 16 ms',async({page,browserName})=>{
 test.skip(browserName!=='chromium','Medición instrumentada ejecutada en Chromium.');test.setTimeout(60000);
 const configuration=emptyConfiguration();const profiles=structuredClone([...builtinProfiles]);for(let i=0;i<5;i++)profiles.push({...structuredClone(builtinProfiles[3]),id:'PER-propio-'+i,name:'Perfil propio '+i,support:'declarada'});
 configuration.profile={...emptyProfiles(),profiles,technologies:Array.from({length:50},(_,i)=>({id:'TEC-'+i,name:'Tecnología '+i,role:'protocolo',purpose:'Propósito de medición',constraints:[],version:'',sources:[],reviewedAt:'',support:'declarada'})),components:Array.from({length:20},(_,i)=>({id:'CMP-'+i,name:'Componente '+i,kind:'otro',responsibility:'Medir',profileId:'perfil-sistema',dependsOn:[],technologyIds:['TEC-'+i]}))};configuration.project!.context.components=configuration.profile.components.map(c=>({id:c.id,text:c.responsibility,status:'pendiente',origin:'user',references:[]}));
 await page.addInitScript(data=>localStorage.setItem('sdd-studio:borrador:v1',JSON.stringify(data)),configuration);const region=await panel(page);const input=region.getByLabel('Propósito de tecnología propia').first();await input.focus();
 const values=await input.evaluate(async element=>{const input=element as HTMLTextAreaElement,samples:number[]=[];const setter=Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype,'value')!.set!;let start=0;const capture=()=>{start=performance.now();},bubble=()=>samples.push(performance.now()-start);document.addEventListener('input',capture,true);document.addEventListener('input',bubble);for(let i=0;i<200;i++){setter.call(input,'Propósito '+i);input.dispatchEvent(new Event('input',{bubbles:true}));await new Promise(resolve=>setTimeout(resolve,17));}document.removeEventListener('input',capture,true);document.removeEventListener('input',bubble);return samples;});values.sort((a,b)=>a-b);const p95=values[Math.ceil(values.length*.95)-1];console.log('Rendimiento H4:',JSON.stringify({samples:200,p95}));expect(p95).toBeLessThan(16);await expect(input).toHaveValue('Propósito 199');await region.getByRole('button',{name:'Guardar tecnología propia',exact:true}).first().click();await expect.poll(()=>page.evaluate(()=>JSON.parse(localStorage.getItem('sdd-studio:borrador:v1')??'{}').profile?.technologies[0]?.purpose)).toBe('Propósito 199');
});

test('perfil propio conserva listas multilínea y metadatos al guardar y exportar',async({page})=>{
 const region=await panel(page);await region.getByRole('button',{name:'Añadir perfil propio',exact:true}).click();await region.getByLabel('Nombre del perfil propio').fill('Instrumento especializado');
 const capabilities=region.getByLabel('Capacidades del perfil propio, una por línea');await capabilities.fill('Capturar mediciones');await capabilities.press('End');await capabilities.press('Enter');await capabilities.pressSequentially('Conservar calibración');await expect(capabilities).toHaveValue('Capturar mediciones\nConservar calibración');
 await region.getByLabel(/Versión declarada de PER-/).fill('Revisión A');await region.getByLabel(/Fecha de revisión de PER-/).fill('2026-10-08');await region.getByLabel(/Fuentes HTTPS de PER-/).fill('https://example.com/protocolo');await region.getByRole('button',{name:'Guardar perfil propio',exact:true}).click();
 const [download]=await Promise.all([page.waitForEvent('download'),region.getByRole('button',{name:'Exportar perfiles JSON',exact:true}).click()]);const saved=JSON.parse(await readFile((await download.path())!,'utf8'));expect(saved.profiles[0].support).toBe('declarada');expect(saved.profiles[0].capabilities).toEqual(['Capturar mediciones','Conservar calibración']);expect(saved.profiles[0].reviewedAt).toBe('2026-10-08');expect(saved.profiles[0].sources[0].url).toBe('https://example.com/protocolo');
});
