import { useState } from 'react';
import * as Dialog from '@radix-ui/react-dialog';
import { Settings2, X } from 'lucide-react';
import { useMcpStore } from '../../store/mcpStore';
import { validMcpEndpoint, type McpTransport } from '../../services/mcpClient';
export function McpSettings() {
    const [open, setOpen] = useState(false);
    const [endpoint, setEndpoint] = useState(''); const [transport, setTransport] = useState<McpTransport>('auto');
    const [enabled, setEnabled] = useState(false); const [token, setToken] = useState('');
    const testing = useMcpStore(s => s.testing); const message = useMcpStore(s => s.testMessage);
    const valid = validMcpEndpoint(endpoint);
    function changeOpen(value: boolean) { if (value) { const store = useMcpStore.getState(); setEndpoint(store.preferences.endpoint); setTransport(store.preferences.transport); setEnabled(store.preferences.enabled); setToken(store.token); useMcpStore.setState({ testMessage: '' }); } else setToken(''); setOpen(value); }
    return <Dialog.Root open={open} onOpenChange={changeOpen}><Dialog.Trigger aria-label="Ajustes de MCP"><Settings2 size={16}/></Dialog.Trigger><Dialog.Portal><Dialog.Overlay className="overlay"/><Dialog.Content className="dialog"><Dialog.Title>Inferencia semántica mediante MCP</Dialog.Title><Dialog.Description>Opcional. El análisis local funciona sin conexión. Si activas MCP, se enviarán tu idea y exclusiones al servidor indicado. El resto del kit y tus ajustes no se envían.</Dialog.Description><label className="field"><span>URL del servidor MCP</span><input type="url" value={endpoint} placeholder="http://localhost:3000/sse" onChange={e => setEndpoint(e.target.value)} aria-invalid={!!endpoint && !valid}/></label><p>Destino del envío: {valid ? new URL(endpoint).origin : 'Sin configurar'}. El servidor debe permitir CORS desde este sitio. Usa HTTPS para destinos remotos.</p><label className="field"><span>Transporte</span><select value={transport} onChange={e => setTransport(e.target.value as McpTransport)}><option value="auto">Detección automática</option><option value="streamable-http">HTTP con transmisión</option><option value="sse">SSE heredado</option></select></label><label className="field"><span>Credencial de sesión opcional</span><input type="password" autoComplete="off" value={token} onChange={e => setToken(e.target.value)}/></label><p>Solo se conserva en memoria hasta cerrar o recargar. No introduzcas claves de proveedores de IA.</p><label className="mcp-consent"><input type="checkbox" checked={enabled} onChange={e => setEnabled(e.target.checked)}/>Activar MCP y permitir el envío de mi idea y exclusiones a este destino</label><p role="status">{message}</p><div className="dialog-actions"><button disabled={!valid || testing} onClick={() => void useMcpStore.getState().testConnection({ enabled, endpoint, transport }, token)}>{testing ? 'Probando conexión…' : 'Probar conexión sin enviar idea'}</button><button disabled={enabled && !valid} onClick={() => { useMcpStore.getState().configure({ enabled, endpoint, transport }, token); changeOpen(false); }}>Guardar ajustes</button><Dialog.Close>Cancelar</Dialog.Close></div><Dialog.Close className="close-icon" aria-label="Cerrar"><X size={18}/></Dialog.Close></Dialog.Content></Dialog.Portal></Dialog.Root>;
}
