import { contextKinds, type ProjectDefinition } from '../domain/projectDefinition';
import { textSection, tableCell, type KitContext } from './kitContext';
const labels = {components:'Componentes',actors:'Actores',capabilities:'Capacidades',processes:'Procesos',entities:'Datos y entidades',rules:'Reglas de negocio',decisions:'Decisiones',assumptions:'Supuestos',questions:'Preguntas pendientes',exclusions:'Exclusiones',contracts:'Contratos declarados'};
const origins = {user:'Usuario',preset:'Conjunto',local:'Regla local','mcp-accepted':'Sugerencia MCP aceptada'};
const modes = {nuevo:'Proyecto nuevo',ampliacion:'Ampliación existente',migracion:'Migración',documentacion:'Documentación o diagnóstico'};
export const activeRequirements = (project: ProjectDefinition) => project.requirements.filter(r=>r.status!=='descartado');
export function projectContext(project: ProjectDefinition): string {
 return contextKinds.map(kind=>`### ${labels[kind]}\n\n${project.context[kind].filter(i=>i.status!=='descartado').map(i=>`- ${i.id}: ${textSection(i.text)} (${i.status}; origen: ${origins[i.origin]}).${i.references.length?` Referencias: ${i.references.join(', ')}.`:''}`).join('\n')||'Pendiente de definir o justificar su no aplicabilidad.'}`).join('\n\n');
}
export function structuredSpec(ctx: KitContext): string {
 const c=ctx.config,p=c.project!;
 const actors=new Map(p.context.actors.map(a=>[a.id,a]));
 const requirements=activeRequirements(p);
 return `# Especificación — ${textSection(c.name)}\n\nEstado: DOCUMENT. Implementación pendiente de autorización explícita. Modelo canónico v${p.schemaVersion}; revisión ${c.revision}.\n\n## Problema y propósito\n\n${textSection(c.idea)}\n\n## Modo y aplicabilidad\n\n${modes[p.mode]}. ${p.implementationRequired?'Implementación de software prevista; no autorizada.':'Trabajo documental sin implementación de software. Las tareas de código no aplican.'}\n\n## Alcance original aportado\n\n${textSection(c.positive)}\n\n## Exclusiones originales\n\n${textSection(c.negative)}\n\n## Contexto declarado\n\n${projectContext(p)}\n\n## Requisitos y criterios\n\n${requirements.map(r=>`### ${r.id} — ${textSection(r.title)}\n\nTipo: ${r.kind==='functional'?'Funcional':'No funcional'}. Prioridad: ${r.priority}. Estado: ${r.status}. Origen: ${origins[r.origin]}.\n\nActor: ${textSection(actors.get(r.actorId)?.text??'')} (${r.actorId||'pendiente'}).\n\nContexto y condición: ${textSection(r.context)}\n\nComportamiento esperado: ${textSection(r.behavior)}\n\nExcepciones y rechazos:\n${r.exceptions.map(text=>'- '+textSection(text)).join('\n')||'- Pendientes de definir o justificar.'}\n\nReglas: ${r.ruleIds.join(', ')||'Pendientes'}. Componentes: ${r.componentIds.join(', ')||'Pendientes'}. Decisiones: ${r.decisionIds.join(', ')||'Pendientes'}. Contratos: ${r.contractIds.join(', ')||'Pendientes'}.\n\n| Criterio | Resultado observable | Ejecución |\n|---|---|---|\n${r.criteria.map(criterion=>`| ${criterion.id} | ${tableCell(criterion.text)} | No ejecutado |`).join('\n')||'| Pendiente | Definir un resultado observable | No ejecutado |'}`).join('\n\n')||'No hay requisitos declarados; deben concretarse antes de implementar.'}\n\n## Puerta de revisión\n\nConfirmar requisitos, criterios y decisiones pendientes con el usuario. Confirmado significa declarado, no implementado ni verificado. No inventar reglas, contratos o evidencia.\n`;
}
export function structuredPlan(ctx: KitContext): string {
 const p=ctx.config.project!;
 return `## Modelo de trabajo declarado\n\nModo: ${modes[p.mode]}. Identidad: ${p.projectId}. Revisión documental: ${ctx.config.revision}.\n\n${p.mode==='nuevo'?'El árbol técnico sigue siendo una propuesta.':'Inspeccionar lo existente y conservar sus interfaces; el árbol propuesto no autoriza una reescritura.'}\n\n## Contexto y contratos aportados\n\n${projectContext(p)}\n\n## Cobertura del comportamiento\n\n${activeRequirements(p).map(r=>`- ${r.id}: ${textSection(r.behavior)}. Criterios: ${r.criteria.map(c=>c.id).join(', ')||'Pendientes'}. Decisiones: ${r.decisionIds.join(', ')||'Pendientes'}. Contratos: ${r.contractIds.join(', ')||'Pendientes'}.`).join('\n')||'Pendiente de requisitos.'}\n\nLa validación sintáctica no resuelve la viabilidad ni sustituye la revisión del dominio.\n`;
}
