import type { Field } from '../../domain/models';
import { fieldLabels, technologyById } from '../../catalog/technologies';
import { tableCell, textSection, type KitContext } from '../kitContext';
import { documentLink } from '../references';
import { designTokens } from './plan';
export function governanceTemplate(path: string, ctx: KitContext): string {
    const link = (to: string, label = to) => documentLink(path, to, label);
    switch (path) {
        case 'docs/BASE_ARCHITECTURE.md': return `# Arquitectura base propuesta\n\nProyecto: ${textSection(ctx.config.name)}. Familia: ${ctx.profile.family}. Arquitectura real: pendiente de inspección. Ningún archivo de código se ha observado ni implementado.\n\n## Módulos propuestos\n\n| Área | Rutas propuestas | Estado |\n|---|---|---|\n| Dominio y flujo | ${ctx.profile.domainFiles.join(', ')} | Propuesto |\n| Persistencia | ${ctx.profile.storageFiles.join(', ')} | Propuesto; contratos pendientes |\n\n## Árbol del destino\n\n\`\`\`text\n${ctx.profile.paths.join('\n')}\n\`\`\`\n\n## Responsabilidades\n\nValidar en fronteras, separar presentación/dominio/almacenamiento y definir permisos antes de código. Si existe servidor, es autoridad de acceso y validación. El cliente no conserva secretos operativos.\n\n## Diseño\n\n${designTokens(ctx)}\n\nEl árbol describe propuestas; el kit contiene documentación. Tras inspección, registrar diferencias en ${link('docs/BASE_OBSERVATIONS.md', 'observaciones')} y decisiones en ${link('docs/DECISIONS.md', 'decisiones')}. ${link(`${ctx.folder}/plan.md`, 'Plan activo')}.\n`;
        case 'docs/BASE_OBSERVATIONS.md': return `# Observaciones del repositorio objetivo\n\nEstado: pendiente de inspección. No se ha leído el repositorio objetivo ni se transfieren hallazgos de otro proyecto.\n\n| Fecha | Observación verificada | Archivo/evidencia | Consecuencia | Estado |\n|---|---|---|---|---|\n| Pendiente | Sin observaciones registradas | Pendiente | Inspeccionar antes de implementar | Pendiente |\n\n## Lista de inspección\n\n- Comprobar herramientas seleccionadas, versiones y dependencias reales.\n- Contrastar ${ctx.profile.family} y las rutas propuestas con lo existente.\n- Revisar dominio, almacenamiento, contratos y permisos.\n- Revisar secretos y pruebas reales.\n${ctx.profile.visual ? '- Inspeccionar semántica, diseño, teclado, estados y adaptación de interfaz.\n' : '- Inspeccionar ayudas, errores y efectos operativos; no exigir una auditoría visual web.\n'}\nUn hallazgo no autoriza corregirlo. Vincular cambios a spec/plan/tasks y respetar la fase registrada en ${link('docs/PROJECT_STATUS.md', 'estado')}.\n`;
        case 'docs/DECISIONS.md': {
            const rows = Object.entries(ctx.config.selections).flatMap(([field, ids]) => ids.map(id => ({ field, id })));
            const origins = { manual: 'Manual', preset: 'Conjunto', inference: 'Inferencia' };
            return `# Registro de decisiones\n\nDecisiones seleccionadas en el configurador; aprobación formal de implementación pendiente. No se atribuye confirmación humana a una inferencia ni a la aplicación de un conjunto.\n\n| ID | Área | Selección | Origen | Aprobación formal |\n|---|---|---|---|---|\n${rows.map((row, index) => `| D-${String(index + 1).padStart(3, '0')} | ${fieldLabels[row.field as Field]} | ${technologyById.get(row.id)?.label ?? tableCell(row.id)} | ${origins[ctx.config.origins[row.field as Field]!] ?? 'No registrado'} | Pendiente |`).join('\n') || '| Pendiente | Pendiente | Sin selecciones | No registrado | Pendiente |'}\n\n## Reglas\n\nRegistrar contexto, alternativas, motivo y quién confirmó únicamente cuando exista información verificable. Mantener decisiones sustituidas y enlazar las nuevas. No cambiar requisitos para justificar defectos ni ampliar alcance con el roadmap. Fecha y referencia Git: no informadas. ${link('docs/PROJECT.md', 'Proyecto')}.\n`;
        }
        case 'docs/ENVIRONMENT_AND_VERIFICATION.md': return `# Entorno y verificaciones propuestas\n\nEntorno, sistema operativo, versiones instaladas y servidor: pendientes de inspección. No hay comandos ejecutados.\n\n## Pila del destino\n\n${ctx.stack}\n\n## Preparación candidata\n\n\`\`\`text\n${ctx.profile.setup}\n\`\`\`\n\nEstos comandos solo se muestran. Revisar versiones, directorio de trabajo, dependencias y autorización antes de usarlos. Activación de entornos depende del sistema.\n\n## Comprobaciones candidatas\n\n${ctx.profile.checks.map(check => '- ' + check).join('\n')}\n\n${ctx.profile.visual ? 'Proponer teclado, foco, contraste y adaptación de la interfaz real; no declarar resultados sin ejecutarlos.' : 'Proponer pruebas de ayudas, argumentos, errores y efectos; adaptación web no aplica.'}\n\nRegistra resultados reales en ${link(`${ctx.folder}/validation.md`, 'validación activa')} y ${link('docs/VERIFICATION.md', 'registro ejecutivo')}. Un comando candidato no es evidencia.\n`;
        case 'docs/PROJECT_STATUS.md': return `# Estado y punto de reanudación\n\n| Campo | Estado inicial |\n|---|---|\n| Proyecto | ${tableCell(ctx.config.name)} |\n| Especificación activa | ${link(`${ctx.folder}/spec.md`, '001')} |\n| Fase | DOCUMENT |\n| Código autorizado | No; pendiente de autorización explícita |\n| Trabajo implementado | Ninguno registrado |\n| Tareas | ${ctx.tasks.length} propuestas, ninguna ejecutada |\n| Evidencia técnica | No ejecutada |\n| Aceptación | Pendiente |\n| Fecha / commit / entorno | No informados |\n| Siguiente paso | Revisar requisitos, contratos, plan y tareas con el usuario |\n\n## Reglas de actualización\n\nRegistrar fase y alcance autorizado, archivos guardados, comprobaciones reales, bloqueos y siguiente paso al cerrar o pausar cada sesión. No guardar credenciales ni declarar implementadas rutas propuestas. Al retomar, inspeccionar repositorio y estado antes de continuar. ${link('prompts/07-resume-pause.md', 'Guía de continuidad')}.\n`;
        case 'docs/ROADMAP.md': return `# Hoja de ruta\n\nNo hay ampliaciones futuras registradas ni autorizadas.\n\n| Propuesta | Motivo | Decisiones necesarias | Estado |\n|---|---|---|---|\n| Ninguna registrada | Pendiente | Pendiente | Sin autorización |\n\nEl alcance y las exclusiones pertenecen a ${link('docs/PROJECT.md', 'PROJECT')}. No convertir exclusiones en futuras funcionalidades ni iniciar ideas del roadmap sin petición del usuario. Cada nueva funcionalidad requiere especificación y autorización separadas.\n`;
        case 'docs/TRACEABILITY.md': return `# Trazabilidad de la especificación 001\n\nEstado: propuesto. Ningún requisito está implementado o verificado por generar este kit.\n\n| RF | Tareas | Archivos propuestos | Evidencia | Estado |\n|---|---|---|---|---|\n${ctx.requirements.map(r => { const tasks = ctx.tasks.filter(t => t.rf.split(', ').includes(r.id)); return `| ${r.id} | ${tasks.map(t => t.id).join(', ')} | ${[...new Set(tasks.flatMap(t => t.files))].join(', ')} | No ejecutada | Propuesto |`; }).join('\n')}\n\n${link(`${ctx.folder}/spec.md`, 'Requisitos')} · ${link(`${ctx.folder}/tasks.md`, 'Tareas')} · ${link(`${ctx.folder}/validation.md`, 'Validación')}\n\nDespués de implementar, sustituir propuestas por rutas y pruebas reales. Resultados unitarios no equivalen a aceptación ni a revisión con lector de pantalla.\n`;
        case 'docs/SDD_VALIDATION.md': return `# Auditoría de cumplimiento SDD\n\nProyecto: ${textSection(ctx.config.name)}. Especificación: 001. Auditoría: No ejecutada; revisor, fecha y evidencia pendientes.\n\n| Comprobación | Resultado | Evidencia |\n|---|---|---|\n| Requisitos y criterios numerados | No ejecutado | Pendiente |\n| Plan, rutas y tareas coherentes | No ejecutado | Pendiente |\n| Autorización, estado y trazabilidad | No ejecutado | Pendiente |\n| Contratos, seguridad y secretos | No ejecutado | Pendiente |\n| ${ctx.profile.visual ? 'Dirección visual, estados y accesibilidad' : 'Ayudas, errores y límites operativos'} | No ejecutado | Pendiente |\n\n## Fuentes a revisar\n\n${link(`${ctx.folder}/spec.md`, 'Especificación')}, ${link(`${ctx.folder}/plan.md`, 'plan')}, ${link(`${ctx.folder}/tasks.md`, 'tareas')}, repositorio real y evidencia técnica.\n\nLa consistencia documental no sustituye comprobar comportamiento ni obtener aceptación del usuario.\n`;
        case 'docs/VERIFICATION.md': return `# Registro ejecutivo de verificaciones\n\nSin ejecuciones registradas. Este archivo no contiene resultados del generador ni de otro proyecto.\n\n| Fecha | Alcance | Comando/método | Entorno | Resultado real | Evidencia | Límites |\n|---|---|---|---|---|---|---|\n| Pendiente | Pendiente | No ejecutado | Pendiente | No ejecutado | Pendiente | Pendiente |\n\nRegistrar únicamente comandos y revisiones realizados, salidas reales y limitaciones. Evidencia detallada: ${link(`${ctx.folder}/validation.md`, 'validación activa')}. Mantener ${link('docs/TRACEABILITY.md', 'trazabilidad')} y ${link('docs/PROJECT_STATUS.md', 'estado')} actualizados. Construcción, verificación técnica y aceptación del usuario son hitos distintos.\n`;
        default: throw new Error('Registro de gobernanza no reconocido.');
    }
}
