import type { Configuration } from '../../domain/models';
import { createKitContext, textSection, type KitContext } from '../kitContext';
import { documentLink } from '../references';
export function designTokens(ctx: KitContext): string {
    const a = ctx.archetype;
    if (!ctx.profile.visual) return 'Estética web: no aplica al destino elegido. Revisar la experiencia operativa pertinente.';
    if (!a) return 'Arquetipo y tokens: pendientes de selección.';
    const labels: Record<string, string> = { background: 'Fondo', surface: 'Superficie', accent: 'Acento', secondaryAccent: 'Acento secundario', foreground: 'Texto', muted: 'Texto secundario', border: 'Borde', heading: 'Fuente de títulos', body: 'Fuente de cuerpo', radius: 'Radio (px)', texture: 'Acabado' };
    return `Arquetipo: ${a.name}\n\n| Token | Valor |\n|---|---|\n${Object.entries(a).filter(([key]) => labels[key]).map(([key, value]) => `| ${labels[key]} | ${value} |`).join('\n')}`;
}
export function planTemplate(c: Configuration, ctx: KitContext = createKitContext(c)): string {
    const path = `${ctx.folder}/plan.md`;
    return `# Plan técnico — ${textSection(c.name)}\n\nEstado: propuesto. Sin implementación autorizada.\n\n${documentLink(path, `${ctx.folder}/spec.md`, 'Especificación')} · ${documentLink(path, 'docs/BASE_ARCHITECTURE.md', 'Arquitectura')}\n\n## Pila seleccionada\n\n${ctx.stack}\n\n## Árbol propuesto del proyecto objetivo\n\n\`\`\`text\n${ctx.config.slug}/\n${ctx.profile.paths.map(p => '  ' + p).join('\n')}\n\`\`\`\n\nEstas rutas son propuestas de implementación, no archivos de código incluidos en el kit.\n\n## Módulos y flujo\n\nFamilia: ${ctx.profile.family}. Entrada validada → lógica de dominio → persistencia elegida → respuesta y errores explícitos. Archivos de dominio: ${ctx.profile.domainFiles.join(', ')}. Persistencia: ${ctx.profile.storageFiles.join(', ')}.\n\n## Contratos\n\nEntradas, entidades, permisos, endpoints y respuestas: pendientes. En destinos con servidor, autorización y validación corresponden al servidor. Django ORM requiere concretar base de datos; no equivale a un motor de persistencia.\n\n## Tokens de diseño\n\n${designTokens(ctx)}\n\n## Adaptación y accesibilidad\n\n${ctx.profile.visual ? 'Si hay interfaz visual: móvil <768 px, tablet 768–1279 px y escritorio ≥1280 px; teclado, foco, AA y objetivos de 44 × 44 px. Revisar contraste real y proponer ajustes explícitos.' : 'No se exige adaptación web a este destino. Verificar ayudas, errores, teclado y límites de actuación pertinentes.'}\n\n## Verificación propuesta\n\n${ctx.profile.checks.map(check => '- ' + check).join('\n')}\n\nHerramientas, versiones y comandos por confirmar tras inspección; nada ejecutado. No inventar evidencia.\n\n## Pendientes\n\nRevisar reglas de negocio, compatibilidades, contratos, versiones y pruebas antes de autorizar código.\n`;
}
