import type { Configuration } from '../../domain/models';
import { archetypeById } from '../../catalog/archetypes';
import { targetTree } from '../targetTree';
import { section } from './spec';
import { selectedStack } from './project';
export function planTemplate(c: Configuration): string {
    const archetype = archetypeById.get(c.selections.archetype?.[0] ?? '');
    const tokens = archetype ? `Arquetipo: ${archetype.name}\n\n| Token | Valor |\n|---|---|\n${Object.entries(archetype).filter(([key]) => !['id', 'name'].includes(key)).map(([key, value]) => `| ${({ background: 'Fondo', surface: 'Superficie', accent: 'Acento', secondaryAccent: 'Acento secundario', foreground: 'Texto', muted: 'Texto secundario', border: 'Borde', heading: 'Fuente de títulos', body: 'Fuente de cuerpo', radius: 'Radio (px)', texture: 'Acabado' } as Record<string, string>)[key]} | ${value} |`).join('\n')}` : c.selections.styling?.includes('not-applicable') ? 'Estética web: no aplica al destino elegido.' : 'Pendiente de seleccionar arquetipo.';
    return `# Plan técnico — ${section(c.name)}\n\nEstado: propuesto. Sin implementación autorizada.\n\n## Pila seleccionada\n\n${selectedStack(c)}\n\n## Árbol propuesto del proyecto objetivo\n\n\`\`\`text\n${c.slug}/\n${targetTree(c).map(path => '  ' + path).join('\n')}\n\`\`\`\n\nEstas rutas son propuestas de implementación, no archivos de código incluidos en el kit.\n\n## Módulos y flujo\n\nEntrada validada → lógica de dominio → persistencia seleccionada → respuesta y errores explícitos. Separar presentación, reglas y almacenamiento. Definir contratos antes de implementar.\n\n## Contratos\n\nEntradas, entidades, permisos y respuestas específicas: pendientes de definición humana. Aplicar validación en fronteras; en destinos con servidor, la autoridad corresponde al servidor.\n\n## Tokens de diseño\n\n${tokens}\n\n## Adaptación y accesibilidad\n\nSi hay interfaz visual: móvil menor de 768 px, tablet de 768 a 1279 px y escritorio desde 1280 px; navegación por teclado, foco visible, contraste AA y objetivos de al menos 44 × 44 px. Verificar el contraste real de la paleta elegida y proponer correcciones explícitas cuando proceda.\n\n## Pruebas\n\nUsar las herramientas seleccionadas para validar requisitos, contratos, errores, persistencia y recorridos reales. Ejecutar construcción, análisis y pruebas; registrar comandos y resultados, nunca inventar evidencia.\n\n## Pendientes\n\nRevisar compatibilidades, versiones declaradas, reglas de negocio y presupuesto de rendimiento antes de código.\n`;
}
