import { literal, template } from '../../i18n/translate';
import type { Configuration } from '../../domain/models';
import { createKitContext, textSection, type KitContext } from '../kitContext';
import { documentLink } from '../references';
export function designTokens(ctx: KitContext): string {
    const a = ctx.archetype;
    if (!ctx.profile.visual) return literal('Estética web: no aplica al destino elegido. Revisar la experiencia operativa pertinente.', ctx.config.sddLanguage);
    if (!a) return literal('Arquetipo y tokens: pendientes de selección.', ctx.config.sddLanguage);
    const labels: Record<string, string> = { background: literal('Fondo', ctx.config.sddLanguage), surface: literal('Superficie', ctx.config.sddLanguage), accent: literal('Acento', ctx.config.sddLanguage), secondaryAccent: literal('Acento secundario', ctx.config.sddLanguage), foreground: literal('Texto', ctx.config.sddLanguage), muted: literal('Texto secundario', ctx.config.sddLanguage), border: literal('Borde', ctx.config.sddLanguage), heading: literal('Fuente de títulos', ctx.config.sddLanguage), body: literal('Fuente de cuerpo', ctx.config.sddLanguage), radius: literal('Radio (px)', ctx.config.sddLanguage), texture: literal('Acabado', ctx.config.sddLanguage) };
    return template(ctx.config.sddLanguage)`Arquetipo: ${a.name}\n\n| Token | Valor |\n|---|---|\n${Object.entries(a).filter(([key]) => labels[key]).map(([key, value]) => `| ${labels[key]} | ${value} |`).join('\n')}`;
}
export function planTemplate(c: Configuration, ctx: KitContext = createKitContext(c)): string {
    const path = `${ctx.folder}/plan.md`;
    return template(ctx.config.sddLanguage)`# Plan técnico — ${textSection(c.name, ctx.config.sddLanguage)}\n\nEstado: propuesto. Sin implementación autorizada.\n\n${documentLink(path, `${ctx.folder}/spec.md`, literal('Especificación', ctx.config.sddLanguage))} · ${documentLink(path, 'docs/BASE_ARCHITECTURE.md', literal('Arquitectura', ctx.config.sddLanguage))}\n\n## Pila seleccionada\n\n${ctx.stack}\n\n## Árbol propuesto del proyecto objetivo\n\n\`\`\`text\n${ctx.config.slug}/\n${ctx.profile.paths.map(p => '  ' + p).join('\n')}\n\`\`\`\n\nEstas rutas son propuestas de implementación, no archivos de código incluidos en el kit.\n\n## Módulos y flujo\n\nFamilia: ${ctx.profile.family}. Entrada validada → lógica de dominio → persistencia elegida → respuesta y errores explícitos. Archivos de dominio: ${ctx.profile.domainFiles.join(', ')}. Persistencia: ${ctx.profile.storageFiles.join(', ')}.\n\n## Contratos\n\nEntradas, entidades, permisos, endpoints y respuestas: pendientes. En destinos con servidor, autorización y validación corresponden al servidor. Django ORM requiere concretar base de datos; no equivale a un motor de persistencia.\n\n## Tokens de diseño\n\n${designTokens(ctx)}\n\n## Adaptación y accesibilidad\n\n${ctx.profile.visual ? literal('Si hay interfaz visual: móvil <768 px, tablet 768–1279 px y escritorio ≥1280 px; teclado, foco, AA y objetivos de 44 × 44 px. Revisar contraste real y proponer ajustes explícitos.', ctx.config.sddLanguage) : literal('No se exige adaptación web a este destino. Verificar ayudas, errores, teclado y límites de actuación pertinentes.', ctx.config.sddLanguage)}\n\n## Verificación propuesta\n\n${ctx.profile.checks.map(check => '- ' + check).join('\n')}\n\nHerramientas, versiones y comandos por confirmar tras inspección; nada ejecutado. No inventar evidencia.\n\n## Pendientes\n\nRevisar reglas de negocio, compatibilidades, contratos, versiones y pruebas antes de autorizar código.\n`;
}
