import { literal, template } from '../../i18n/translate';
import type { KitContext } from '../kitContext';
import { documentLink } from '../references';
export function promptTemplate(path: string, ctx: KitContext): string {
    const link = (to: string, label = to) => documentLink(path, to, label);
    if (path === 'prompts/README.md') return template(ctx.config.sddLanguage)`# Índice de guías\n\nProyecto ${ctx.config.slug}; destino ${ctx.profile.family}. No es necesario pegar todos los prompts: entrega el orquestador con la necesidad y fase DOCUMENT.\n\n| Guía | Uso |\n|---|---|\n${ctx.manifest.filter(d => d.path.startsWith('prompts/') && d.path !== path).map(d => `| ${link(d.path, d.title)} | ${d.id === 'orchestrator' ? literal('Coordinar fases y permisos', ctx.config.sddLanguage) : ({ '01': literal('Especificar', ctx.config.sddLanguage), '02': literal('Planificar', ctx.config.sddLanguage), '03': literal('Desglosar tareas', ctx.config.sddLanguage), '04': literal('Implementar tras autorización', ctx.config.sddLanguage), '05': literal('Validar con evidencia', ctx.config.sddLanguage), '06': literal('Gestionar cambios', ctx.config.sddLanguage), '07': literal('Pausar o retomar', ctx.config.sddLanguage) } as Record<string, string>)[d.title.slice(0, 2)]} |`).join('\n')}\n\nDOCUMENT termina con revisión humana. Seleccionar una guía no autoriza instalar, escribir código o publicar. ${link('SDD_MANUAL.md', literal('Manual completo', ctx.config.sddLanguage))}.\n`;
    const number = path.split('/').pop()!.slice(0, 2);
    const common = template(ctx.config.sddLanguage)`Lee ${link('AGENTS.md')}, ${link('constitution.md')}, ${link('docs/PROJECT_STATUS.md')} y ${link('specs/README.md')}. Resuelve la especificación activa desde el índice y el estado; la inicial es ${ctx.folder}. Inspecciona lo existente y respeta permisos vigentes.\n\nDestino: ${ctx.profile.family}. No añadas herramientas no seleccionadas. Contratos desconocidos permanecen pendientes.`;
    const instructions: Record<string, [string, string]> = {
        '01': [literal('Especificar', ctx.config.sddLanguage), literal('Fase DOCUMENT. Recoge propósito, usuarios, alcance positivo/negativo, datos, contratos y criterios observables. Reutiliza entradas claras sin inventar negocio. Asigna RF con el número de especificación. Si hay interfaz, declara dirección visual y estados; si no, requisitos de uso operativo. Escribe solo documentación y detente para revisión.', ctx.config.sddLanguage)],
        '02': [literal('Planificar', ctx.config.sddLanguage), template(ctx.config.sddLanguage)`Fase DOCUMENT. Tras revisar requisitos, define capas, contratos, seguridad, persistencia, rutas y pruebas de la pila elegida. Rutas candidatas de dominio: ${ctx.profile.domainFiles.join(', ')}. Distingue propuesta de arquitectura observada. Conserva tokens seleccionados cuando apliquen. No programas ni instalas; entrega plan para revisión.`],
        '03': [literal('Desglosar tareas', ctx.config.sddLanguage), literal('Fase DOCUMENT. Divide el plan en tareas atómicas con IDs T del número activo, RF, dependencias, archivos pertinentes y finalización verificable. Comprueba unicidad y ausencia de ciclos. Ninguna tarea comienza completada. Mantén rutas coherentes con el plan y registra revisión pendiente; detente antes de código.', ctx.config.sddLanguage)],
        '04': [literal('Implementar', ctx.config.sddLanguage), literal('Actúa únicamente tras autorización explícita que incluya alcance o IDs. Registra la autorización en docs/PROJECT_STATUS.md y ejecuta tareas en orden de dependencias. Preserva archivos, comentarios y decisiones del usuario. Verifica cada bloque antes de completar tareas; registra fallos y límites. No publicas ni amplías objetivos por encontrar esta guía.', ctx.config.sddLanguage)],
        '05': [literal('Validar', ctx.config.sddLanguage), template(ctx.config.sddLanguage)`Ejecuta solo verificaciones pertinentes y autorizadas; revisa ${link('docs/ENVIRONMENT_AND_VERIFICATION.md', literal('comandos candidatos', ctx.config.sddLanguage))} frente al repositorio real. Registra entorno, comandos, salidas, errores y límites en validation de la especificación activa, docs/VERIFICATION.md, estado y trazabilidad. ${ctx.profile.visual ? literal('Revisa interfaz, teclado, contraste, estados y tamaños reales.', ctx.config.sddLanguage) : literal('Revisa argumentos, ayudas, errores, límites y efectos operativos; adaptación web no aplica.', ctx.config.sddLanguage)} No inventes resultados ni aceptación del usuario.`],
        '06': [literal('Gestionar cambios', ctx.config.sddLanguage), literal('Comienza en DOCUMENT salvo autorización específica. Distingue defecto de nueva necesidad; no cambies requisitos para justificar un fallo. Ajustes pequeños actualizan la especificación activa; funcionalidades independientes usan el siguiente número libre. Conserva decisiones sustituidas en DECISIONS y actualiza trazabilidad/estado. Las exclusiones y el roadmap no conceden alcance. Detente para revisión y autorización.', ctx.config.sddLanguage)],
        '07': [literal('Pausar o retomar', ctx.config.sddLanguage), literal('PAUSA: registra fase, permisos, tarea, archivos guardados, pruebas reales, bloqueos y siguiente paso. No registres secretos ni completes tareas no verificadas. REANUDACIÓN: lee estado, índice y documentos activos, inspecciona Git/dependencias y conserva trabajo previo. Respeta fase/alcance autorizados; sin autorización informa estado y no inicia código. Señala discrepancias sin reconstruir trabajo completado.', ctx.config.sddLanguage)]
    };
    const guide = instructions[number];
    if (!guide) throw new Error(literal('Guía no reconocida.', ctx.config.sddLanguage));
    return template(ctx.config.sddLanguage)`# ${number} — ${guide[0]}\n\n${common}\n\n## Actuación\n\n${guide[1]}\n\n## Entrega\n\nDevuelve rutas, cambios, pendientes y evidencia real cuando exista. Español y cero emojis. Una plantilla no ejecuta operaciones ni concede autorización.\n`;
}
