import { literal, template } from '../../i18n/translate';
import type { KitContext } from '../kitContext';
import { documentLink } from '../references';
export function initialValidation(ctx: KitContext, reusable = false): string {
    return template(ctx.config.sddLanguage)`# Validación — ${reusable ? literal('NNN / Funcionalidad futura', ctx.config.sddLanguage) : '001 / ' + ctx.config.slug}\n\nEstado: No ejecutado. Fecha, entorno, versión de código y persona revisora: pendientes. Aceptación funcional: pendiente. Este registro no contiene resultados del generador.\n\n## Verificaciones previstas\n\n| RF | Comando o método propuesto | Resultado esperado | Resultado observado | Estado |\n|---|---|---|---|---|\n${ctx.profile.checks.map(check => template(ctx.config.sddLanguage)`| ${reusable ? 'RF-NNN-XX' : 'RF-001-01'} | ${check} | Conforme al contrato aprobado | Sin ejecución | No ejecutado |`).join('\n')}\n\n## Uso y accesibilidad\n\n${ctx.profile.visual ? literal('Revisar interfaz real, teclado, foco, contraste, estados y adaptación. Las pruebas de lector de pantalla y navegador deben registrarse según lo ejecutado.', ctx.config.sddLanguage) : literal('Revisar argumentos, ayudas, errores y límites de actuación; no aplicar una revisión responsiva web.', ctx.config.sddLanguage)}\n\n## Evidencia y limitaciones\n\nRegistrar comandos, códigos de salida, resultados observados y límites. No convertir propuestas en resultados positivos ni reutilizar evidencia de otros proyectos. Mantener trazabilidad y estado.\n\n## Aceptación\n\nPendiente de confirmación explícita del usuario después de revisar el comportamiento real.\n`;
}
export function reusableTemplate(path: string, ctx: KitContext): string {
    if (path === 'specs/README.md') return template(ctx.config.sddLanguage)`# Índice de especificaciones\n\n| Número | Proyecto / necesidad | Documentos activos | Estado | Código autorizado |\n|---|---|---|---|---|\n| 001 | ${ctx.config.slug} | ${['spec', 'plan', 'tasks', 'validation'].map(id => documentLink(path, `${ctx.folder}/${id}.md`, id)).join(', ')} | DOCUMENT | No |\n\n## Numeración\n\nPara una funcionalidad nueva, inspecciona carpetas y usa el siguiente número libre. La carpeta inicial es ${ctx.folder}. Cada carpeta contiene spec, plan, tasks y validation. Usa RF-NNN-XX y T-NNN-XX correspondientes al número real.\n\nLas cuatro plantillas en _templates son esqueletos reutilizables; sus marcadores no representan trabajo autorizado. Cambios pequeños actualizan la especificación activa y decisiones; no se borran históricos.\n`;
    const kind = path.split('/').pop()!.replace('.md', '');
    const context = template(ctx.config.sddLanguage)`Contexto del destino: ${ctx.profile.family}.\n\n${ctx.stack}\n\nMarcadores NNN, título, necesidad, contratos y rutas se completan para la nueva funcionalidad. No reutilizar la necesidad inicial como una nueva solicitud ni interpretar esta plantilla como autorización.`;
    if (kind === 'validation') return initialValidation(ctx, true);
    if (kind === 'spec') return template(ctx.config.sddLanguage)`# Plantilla de especificación — NNN / Título pendiente\n\nEstado: DOCUMENT; código no autorizado.\n\n${context}\n\n## Problema, usuarios y recorrido\n\nPendiente de aportar para la nueva funcionalidad.\n\n## Alcance y exclusiones\n\nPendiente; separar necesidades de futuras ideas.\n\n## Requisitos y criterios\n\n| RF | Acción | Resultado verificable |\n|---|---|---|\n| RF-NNN-01 | Pendiente | Pendiente de revisión |\n\n## Datos, permisos y contratos\n\nPendientes; no inventarlos. ${ctx.profile.visual ? literal('Definir dirección visual, estados y accesibilidad cuando aplique.', ctx.config.sddLanguage) : literal('Definir ayudas, errores y límites operativos pertinentes.', ctx.config.sddLanguage)}\n\n## Revisión\n\nDetenerse para revisión humana antes de código.\n`;
    if (kind === 'plan') return template(ctx.config.sddLanguage)`# Plantilla de plan — NNN / Título pendiente\n\nEstado: propuesto, implementación no autorizada.\n\n${context}\n\n## Arquitectura y archivos\n\nDefinir módulos y rutas para la funcionalidad nueva dentro de la arquitectura seleccionada. La base de dominio actual propuesta usa ${ctx.profile.domainFiles.join(', ')}; no atribuir existencia sin inspeccionar.\n\n## Contratos y fronteras\n\nEntradas, respuestas, almacenamiento y permisos: pendientes. Autoridad de servidor cuando exista.\n\n## Diseño y uso\n\n${ctx.profile.visual ? literal('Adaptar los tokens seleccionados, estados, teclado y contraste al alcance nuevo.', ctx.config.sddLanguage) : literal('No exigir diseño web; definir uso operativo, ayudas y errores.', ctx.config.sddLanguage)}\n\n## Verificación\n\nElegir comprobaciones según la pila y los criterios reales. Ningún comando ejecutado.\n`;
    if (kind === 'tasks') return template(ctx.config.sddLanguage)`# Plantilla de tareas — NNN / Título pendiente\n\n${context}\n\n- [ ] [T-NNN-01] Acción atómica pendiente de definir\n  - RF: RF-NNN-01.\n  - Depende de: pendiente según grafo aprobado.\n  - Archivos previstos: rutas de la funcionalidad nueva por definir.\n  - Finaliza cuando: resultado observable y comprobación concreta por revisar.\n\nNo marcar tareas ejecutadas al generar una plantilla. Numerar con la especificación real, comprobar dependencias sin ciclos y autorizar implementación después de revisión.\n`;
    throw new Error(literal('Plantilla reutilizable no reconocida.', ctx.config.sddLanguage));
}
