import { designMetadata } from './plan';
import { literal, template } from '../../i18n/translate';
import { textSection, type KitContext } from '../kitContext';
import { documentLink } from '../references';
import { treeLines } from '../kitTree';
import { designTokens } from './plan';
export function rootTemplate(path: string, ctx: KitContext): string {
    const link = (to: string, label = to) => documentLink(path, to, label);
    const identity = `${textSection(ctx.config.name, ctx.config.sddLanguage)} (${ctx.config.slug})`;
    switch (path) {
        case 'README.md': return template(ctx.config.sddLanguage)`# ${identity}\n\nKit de desarrollo guiado por especificaciones. Estado: DOCUMENT, código no autorizado.\n\n## Propósito\n\n${textSection(ctx.config.idea.slice(0, 800), ctx.config.sddLanguage)}\n\n## Estructura\n\n\`\`\`text\n${treeLines(ctx.manifest)}\n\`\`\`\n\n## Inicio\n\nAbre esta carpeta y entrega ${link('prompts/00-orchestrator.md', literal('el orquestador', ctx.config.sddLanguage))} a tu agente. Lee ${link('AGENTS.md')}, ${link('constitution.md')} y ${link('TECHNICAL_CONTEXT.md')}. Revisa la ${link(`${ctx.folder}/spec.md`, literal('especificación activa', ctx.config.sddLanguage))}, el plan y las tareas antes de autorizar código.\n\n## Pila declarada\n\n${ctx.stack}\n\n## Ciclo de trabajo\n\nDOCUMENT → revisión humana → autorización delimitada → IMPLEMENT → VALIDATE. Para cambios o continuidad usa las guías del ${link('prompts/README.md', literal('índice de prompts', ctx.config.sddLanguage))}.\n\n${link('SDD_MANUAL.md', literal('Manual completo', ctx.config.sddLanguage))} · ${link('MANUAL-PARA-USUARIO.txt', literal('Guía breve', ctx.config.sddLanguage))} · ${link('docs/PROJECT_STATUS.md', literal('Estado', ctx.config.sddLanguage))}\n\nEl kit entrega documentos, no los archivos de código dibujados en el plan. No hay pruebas ni inspección del destino ejecutadas.\n`;
        case 'AGENTS.md': return template(ctx.config.sddLanguage)`# Instrucciones para agentes — ${identity}\n\n## Lectura inicial\n\nLee ${['AGENTS.md', 'docs/PROJECT_STATUS.md', `${ctx.folder}/spec.md`].map(p => link(p)).join(', ')} únicamente al iniciar. Después identifica la tarea y consulta solo su dominio y contratos públicos. Inspecciona repositorio, dependencias y Git antes de decidir qué existe.\n\n## Pila y alcance\n\n${ctx.stack}\n\nSolo herramientas seleccionadas y requisitos aprobados. No instales bibliotecas ni amplíes objetivos sin autorización. Contratos y versiones no definidos quedan pendientes.\n\n## DOCUMENT\n\nRevisa spec → plan → tasks, actualiza estado/decisiones/trazabilidad y detente para revisión. La existencia de estos archivos no autoriza código. Nuevas funcionalidades utilizan la siguiente carpeta numerada libre.\n\n## IMPLEMENT\n\nRequiere autorización explícita registrada, con tareas y límites. Ejecuta por dependencias, preserva cambios/comentarios del usuario y verifica antes de marcar completado. Rutas propuestas de dominio: ${ctx.profile.domainFiles.join(', ')}.\n\n## VALIDATE\n\nRegistra comandos, entorno, salidas y límites reales en la validación activa y VERIFICATION. Nunca copies resultados de otra aplicación. Aceptación y publicación se autorizan por separado.\n\n## Reglas del destino\n\n${ctx.profile.visual ? literal('Diseño deliberado, tokens seleccionados, estados de interfaz, teclado, foco y contraste verificable. No imponer un framework distinto.', ctx.config.sddLanguage) : literal('Priorizar ayudas, errores y controles operativos. La adaptación visual web no aplica a este destino.', ctx.config.sddLanguage)}\n\nEn proyectos con servidor, validación y autorización son responsabilidad del servidor; en clientes autónomos no inventes un backend. Protege secretos, usa datos sintéticos y simulación previa para operaciones con efectos cuando corresponda. Español y cero emojis. Si hay interfaz React, iconos exclusivamente lucide-react.\n`;
        case 'TECHNICAL_CONTEXT.md': return template(ctx.config.sddLanguage)`# Contexto técnico — ${identity}\n\n## Selecciones del destino\n\n${ctx.stack}\n\n## Diseño declarado\n\n${designMetadata(ctx)}\n\nFamilia de arquitectura: ${ctx.profile.family}.\n\n## Fronteras de responsabilidad\n\n${ctx.config.selections.architecture?.includes('client') ? literal('Arquitectura cliente: persistencia y controles locales según selección. No existe un servidor propio por asumirlo en una plantilla.', ctx.config.sddLanguage) : literal('Confirmar capas cliente/servidor, contratos y permisos. Si hay servidor, mantiene autoridad sobre datos, validación y acceso.', ctx.config.sddLanguage)}\n\nDominio: ${ctx.profile.domainFiles.join(', ')}. Persistencia propuesta: ${ctx.profile.storageFiles.join(', ')}.\n\n## Dirección visual\n\n${designTokens(ctx)}\n\n## Integración y límites\n\nLos protocolos, APIs y complementos seleccionados son decisiones del proyecto objetivo. No se instalan ni ejecutan por generar este kit. Concretar compatibilidad/versiones antes de implementación. Django ORM necesita una base de datos elegida; para cualquier stack sin receta, concretar archivos y comandos tras inspección.\n\nConsulta ${link('docs/BASE_ARCHITECTURE.md', literal('arquitectura', ctx.config.sddLanguage))} y ${link('docs/ENVIRONMENT_AND_VERIFICATION.md', literal('entorno y comprobaciones', ctx.config.sddLanguage))}.\n`;
        case 'SDD_MANUAL.md': return template(ctx.config.sddLanguage)`# Manual SDD — ${identity}\n\n## 1. Inicio\n\nExtrae el ZIP, abre la carpeta en el editor y entrega ${link('prompts/00-orchestrator.md', literal('el orquestador', ctx.config.sddLanguage))}. El ${link('specs/README.md', literal('índice', ctx.config.sddLanguage))} identifica la especificación activa. Lee alcance y exclusiones; no presupongas contratos de negocio.\n\n## 2. Documentar\n\nUsa las guías 01, 02 y 03 del ${link('prompts/README.md', literal('índice de prompts', ctx.config.sddLanguage))}. El agente revisa requisitos, arquitectura y tareas en ese orden. Entrega documentación y espera tu aprobación; no instala ni programa.\n\n## 3. Revisar y autorizar\n\nComprueba pila, rutas, criterios, seguridad y pruebas previstas. Autoriza expresamente tareas concretas o el alcance completo y registra la autorización en ${link('docs/PROJECT_STATUS.md', literal('el estado', ctx.config.sddLanguage))}. Una selección del configurador no sustituye esa aprobación.\n\n## 4. Implementar\n\nUsa ${link('prompts/04-implement.md', literal('04-implementar', ctx.config.sddLanguage))}. Trabaja por dependencias y verifica cada bloque. Familia: ${ctx.profile.family}; archivos de dominio propuestos: ${ctx.profile.domainFiles.join(', ')}. Solo usa herramientas elegidas.\n\n## 5. Verificar y aceptar\n\nUsa ${link('prompts/05-validate.md', literal('05-validar', ctx.config.sddLanguage))}. Los comandos de ${link('docs/ENVIRONMENT_AND_VERIFICATION.md', literal('entorno', ctx.config.sddLanguage))} son candidatos por confirmar, no ejecuciones aprobadas. Registra evidencia real en ${link(`${ctx.folder}/validation.md`, literal('la validación activa', ctx.config.sddLanguage))}. Revisa resultados y confirma aceptación por separado; no se publica automáticamente.\n\n## 6. Cambios\n\nUsa ${link('prompts/06-changes.md', literal('06-cambios', ctx.config.sddLanguage))}. Ajustes pequeños mantienen la especificación activa; funcionalidades nuevas utilizan el siguiente número libre, con RF/T asociados. Roadmap y exclusiones no conceden alcance.\n\n## 7. Pausar y retomar\n\nUsa ${link('prompts/07-resume-pause.md', literal('07-pausa/reanudación', ctx.config.sddLanguage))}. Registra fase, tareas, archivos guardados, pruebas reales y siguiente paso. Al retomar, inspecciona Git y respeta permisos vigentes.\n\n## Reglas de evidencia\n\nInspección, implementación, verificación y aceptación son estados distintos. No rellenes resultados con expectativas, no registres credenciales y no atribuyas a este proyecto resultados del generador.\n`;
        case 'MANUAL-PARA-USUARIO.txt': return template(ctx.config.sddLanguage)`GUÍA BREVE — ${identity}\n\n1. Extrae el kit y abre su carpeta en el editor.\n2. Entrega prompts/00-orchestrator.md al agente y comienza en DOCUMENT.\n3. Revisa ${ctx.folder}/spec.md, plan.md y tasks.md.\n4. Aclara pendientes y autoriza expresamente el código antes de instalar o implementar.\n5. Pide verificaciones reales y revisión de los criterios; aceptar y publicar son decisiones posteriores.\n6. Para pausar/retomar usa prompts/07-resume-pause.md y docs/PROJECT_STATUS.md.\n\nDestino: ${ctx.profile.family}. Herramientas y versiones dependen de tu selección; no necesitas npm por utilizar este kit si tu destino usa otra pila.\n\nLos archivos de código del árbol del plan son propuestas. El ZIP solo contiene documentación. Español, cero emojis, secretos protegidos y alcance delimitado. Consulta SDD_MANUAL.md para el flujo completo.\n`;
        default: throw new Error(literal('Documento raíz no reconocido.', ctx.config.sddLanguage));
    }
}
