import { useTranslation } from '../i18n/useTranslation';
import { Command, ArrowUpRight, GitBranch, ShieldCheck } from 'lucide-react';
import { useUIStore } from '../store/uiStore';
import { PanelNavigation } from '../components/navigation/PanelNavigation';
import { Configurator } from '../components/configurator/Configurator';
import { IdeaEditor } from '../components/storyteller/IdeaEditor';
import { DocumentCanvas } from '../components/documents/DocumentCanvas';
import { CommandPalette } from '../components/command/CommandPalette';
export function StudioLayout() { const { t } = useTranslation(); const panel = useUIStore(s => s.panel); return <><header className="studio-header"><a className="brand" href={import.meta.env.BASE_URL}><span className="brand-mark"><GitBranch size={20}/></span><span>SDD<span className="brand-light">—Studio</span><small>{t("DEL CONCEPTO AL CONTRATO")}</small></span></a><div className="header-meta"><span className="local-pill"><ShieldCheck size={14}/>  {t("Generación local")}</span><button aria-label={t('Buscar en el estudio')} className="search-trigger" onClick={() => useUIStore.setState({ palette: true })}><Command size={16}/><span>{t("Buscar")}</span><kbd>Ctrl K</kbd></button><a className="repository-link" href="https://github.com/xaviiromf/SDD-generator" target="_blank" rel="noreferrer" aria-label={t("Ver repositorio en GitHub")}><ArrowUpRight size={18}/></a></div></header><div className="workspace-heading"><div><span className="eyebrow">{t("ESPACIO DE TRABAJO / 001")}</span><h1>{t("Una idea. Un plan claro.")}</h1></div><p>{t("Especificaciones para construir")}<br />{t("con intención.")}</p></div><PanelNavigation /><main className={`workspace active-${panel}`}><section className="studio-panel config-panel" aria-label={t("Configuración")}><div className="panel-title"><span>01</span><h2>{t("Define el sistema")}</h2><small>{t("7 fases")}</small></div><div className="panel-body"><Configurator /></div></section><section className="studio-panel idea-panel" aria-label={t("Idea del proyecto")}><div className="panel-title"><span>02</span><h2>{t("Cuenta tu idea")}</h2><small>{t("Lenguaje natural")}</small></div><div className="panel-body"><IdeaEditor /></div></section><section className="studio-panel docs-panel" aria-label={t("Documentos SDD")}><div className="panel-title"><span>03</span><h2>{t("Revisa el contrato")}</h2><small>{t("Generación local")}</small></div><DocumentCanvas /></section></main><footer className="studio-footer"><span>SDD-STUDIO <small>{t("Generador determinista")}</small></span><span>{t("Especifica. Revisa. Autoriza. Construye.")}</span></footer><CommandPalette /></>; }
